import type { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Container from '@/components/Container'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of Service for Granted AI. Read the terms governing your use of our grant writing platform.',
  alternates: { canonical: 'https://grantedai.com/terms' },
}

export default function TermsPage() {
  return (
    <>
      <Header />
      <main>
        <section className="bg-navy text-white">
          <Container className="py-28 text-center md:py-36">
            <h1 className="heading-xl text-white">Terms of Service</h1>
            <p className="body-lg mt-4 text-white/60">Last updated: February 7, 2026</p>
          </Container>
        </section>

        <Container className="py-20 md:py-28">
          <div className="prose prose-navy mx-auto max-w-3xl">
            <h2 className="heading-md mb-4">1. Acceptance of Terms</h2>
            <p className="body-lg text-navy-light mb-8">
              By accessing or using Granted AI (&ldquo;the Service&rdquo;), operated by Granted AI (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>

            <h2 className="heading-md mb-4">2. Description of Service</h2>
            <p className="body-lg text-navy-light mb-8">
              Granted AI is an AI-powered grant writing platform that helps users analyze RFPs, receive guided coaching, and generate grant proposal drafts. The Service is provided via grantedai.com and app.grantedai.com.
            </p>

            <h2 className="heading-md mb-4">3. Account Registration</h2>
            <p className="body-lg text-navy-light mb-8">
              You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary.
            </p>

            <h2 className="heading-md mb-4">4. Subscription &amp; Payment</h2>
            <p className="body-lg text-navy-light mb-4">
              Granted offers paid subscription plans billed on a monthly or annual basis. All plans include a 7-day free trial. By subscribing, you authorize us to charge your payment method through Stripe on a recurring basis until you cancel.
            </p>
            <p className="body-lg text-navy-light mb-8">
              You may cancel your subscription at any time. Upon cancellation, you retain access through the end of your current billing period. Refunds are not provided for partial billing periods unless required by applicable law.
            </p>

            <h2 className="heading-md mb-4">5. Acceptable Use</h2>
            <p className="body-lg text-navy-light mb-4">
              You agree not to:
            </p>
            <ul className="body-lg text-navy-light mb-8 list-disc pl-6 space-y-2">
              <li>Use the Service for any unlawful purpose or to submit fraudulent grant applications</li>
              <li>Misrepresent your identity, qualifications, or organizational affiliations in generated proposals</li>
              <li>Attempt to reverse-engineer, decompile, or extract the source code of the Service</li>
              <li>Interfere with or disrupt the Service&rsquo;s infrastructure</li>
              <li>Use automated means to access the Service beyond its intended interface</li>
              <li>Resell, sublicense, or redistribute generated content as a competing service</li>
            </ul>

            <h2 className="heading-md mb-4">6. Your Content &amp; Intellectual Property</h2>
            <p className="body-lg text-navy-light mb-4">
              You retain ownership of all content you upload to or create through the Service, including RFPs, coaching answers, organizational data, and the resulting proposal drafts. By using the Service, you grant us a limited license to process your content solely for the purpose of providing the Service to you.
            </p>
            <p className="body-lg text-navy-light mb-8">
              We do not claim ownership of your proposals. You are solely responsible for the accuracy, completeness, and suitability of any grant application you submit based on content generated by Granted.
            </p>

            <h2 className="heading-md mb-4">7. AI-Generated Content Disclaimer</h2>
            <p className="body-lg text-navy-light mb-8">
              Proposals generated by Granted are drafts intended as starting points for your review and refinement. AI-generated content may contain errors, omissions, or inaccuracies. You are responsible for reviewing, editing, and verifying all generated content before submission to any funding agency. Granted does not guarantee that any proposal will be funded.
            </p>

            <h2 className="heading-md mb-4">8. Privacy</h2>
            <p className="body-lg text-navy-light mb-8">
              Your use of the Service is also governed by our{' '}
              <a href="/privacy" className="underline font-semibold text-navy hover:text-teal transition-colors">
                Privacy Policy
              </a>
              , which describes how we collect, use, and protect your information.
            </p>

            <h2 className="heading-md mb-4">9. Disclaimer of Warranties</h2>
            <p className="body-lg text-navy-light mb-8">
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY PROPOSAL GENERATED WILL RESULT IN GRANT FUNDING.
            </p>

            <h2 className="heading-md mb-4">10. Limitation of Liability</h2>
            <p className="body-lg text-navy-light mb-8">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, GRANTED AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>

            <h2 className="heading-md mb-4">11. Indemnification</h2>
            <p className="body-lg text-navy-light mb-8">
              You agree to indemnify and hold harmless Granted AI, its officers, directors, employees, and agents from any claims, liabilities, damages, losses, or expenses (including reasonable attorneys&rsquo; fees) arising from your use of the Service, your violation of these Terms, or your submission of proposals based on content generated by the Service.
            </p>

            <h2 className="heading-md mb-4">12. Termination</h2>
            <p className="body-lg text-navy-light mb-8">
              We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason at our sole discretion, with or without notice. Upon termination, your right to use the Service ceases immediately. Sections 6, 7, 9, 10, 11, and 13 survive termination.
            </p>

            <h2 className="heading-md mb-4">13. Governing Law &amp; Disputes</h2>
            <p className="body-lg text-navy-light mb-8">
              These Terms are governed by the laws of the State of Delaware, without regard to its conflict of laws provisions. Any disputes arising under these Terms shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association, except that either party may seek injunctive relief in any court of competent jurisdiction.
            </p>

            <h2 className="heading-md mb-4">14. Changes to These Terms</h2>
            <p className="body-lg text-navy-light mb-8">
              We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on this page with a revised &ldquo;Last updated&rdquo; date and, for significant changes, by email. Continued use of the Service after changes constitutes acceptance of the updated Terms.
            </p>

            <h2 className="heading-md mb-4">15. Contact Us</h2>
            <p className="body-lg text-navy-light">
              If you have questions about these Terms of Service, contact us at:
            </p>
            <p className="body-lg text-navy-light mt-2">
              <strong>Granted AI</strong><br />
              Email: support@grantedai.com
            </p>
          </div>
        </Container>
      </main>
      <Footer />
    </>
  )
}
